name: Style

on:
  push:
    branches:
      - master
    paths:
      - "**.cpp"
      - "**.hpp"
  pull_request:
    branches:
      - master
    paths:
      - "**.cpp"
      - "**.hpp"

jobs:
  check-format:
    name: "Check style"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install format dependencies
        run: pip3 install clang-format==17.0.6

      - name: Configure
        run: cmake -S . -DDISABLE_BUILDING_EXECUTABLE=1 -B building_format

      - name: Check style
        run: cmake --build building_format --target check-format